# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: TheMoneroDeveloperCommunity.MoneroGUIWallet
PackageVersion: 0.18.2.2
PackageLocale: en-US
Publisher: The Monero Developer Community
PackageName: Monero GUI Wallet
License: The Monero Developer Community
LicenseUrl: https://github.com/monero-project/monero-gui/blob/v0.18.2.2/LICENSE
Copyright: Copyright (c) 2014-2022, The Monero Project
ShortDescription: Monero GUI Wallet Setup
ManifestType: defaultLocale
ManifestVersion: 1.4.0
